//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindTheBooty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hunt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hunt()
        {
            this.badges = new HashSet<badge>();
            this.treasures = new HashSet<treasure>();
            this.user_hunt_relation = new HashSet<user_hunt_relation>();
        }
    
        public int hunt_id { get; set; }
        public Nullable<int> sponsor_sponsor_id { get; set; }
        public string hunt_name { get; set; }
        public string hunt_type { get; set; }
        public System.DateTime time_create { get; set; }
        public System.DateTime time_expire { get; set; }
        public int max_users { get; set; }
        public int multi_single { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<badge> badges { get; set; }
        public virtual sponsor sponsor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<treasure> treasures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_hunt_relation> user_hunt_relation { get; set; }
    }
}
