//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindTheBooty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_setting_relation
    {
        public string user_user_id { get; set; }
        public string user_setting_name { get; set; }
        public string setting_value { get; set; }
    
        public virtual user user { get; set; }
        public virtual user_setting user_setting { get; set; }
    }
}
