//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindTheBooty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_hunt_relation
    {
        public string user_user_id { get; set; }
        public int hunt_hunt_id { get; set; }
        public string active { get; set; }
        public string completed { get; set; }
    
        public virtual hunt hunt { get; set; }
        public virtual user user { get; set; }
    }
}
