//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindTheBooty.Models.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class award
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public award()
        {
            this.badges = new HashSet<badge>();
            this.user_award_relation = new HashSet<user_award_relation>();
        }
    
        public int award_id { get; set; }
        public int treasure_treasure_id { get; set; }
        public int treasure_hunt_hunt_id { get; set; }
        public int points { get; set; }
    
        public virtual treasure treasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<badge> badges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_award_relation> user_award_relation { get; set; }
    }
}
