//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindTheBooty.Models.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class badge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public badge()
        {
            this.user_badge_relation = new HashSet<user_badge_relation>();
        }
    
        public int badge_id { get; set; }
        public int award_award_id { get; set; }
        public int hunt_hunt_id { get; set; }
        public int treasure_treasure_id { get; set; }
        public int treasure_hunt_hunt_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual award award { get; set; }
        public virtual hunt hunt { get; set; }
        public virtual treasure treasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_badge_relation> user_badge_relation { get; set; }
    }
}
