//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindTheBooty.Models.GeneratedModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FindTheBooty_prodEntities : DbContext
    {
        public FindTheBooty_prodEntities()
            : base("name=FindTheBooty_prodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<badge> badges { get; set; }
        public virtual DbSet<hunt> hunts { get; set; }
        public virtual DbSet<sponsor> sponsors { get; set; }
        public virtual DbSet<treasure> treasures { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_badge_relation> user_badge_relation { get; set; }
        public virtual DbSet<user_hunt_relation> user_hunt_relation { get; set; }
        public virtual DbSet<user_setting> user_setting { get; set; }
        public virtual DbSet<user_setting_relation> user_setting_relation { get; set; }
        public virtual DbSet<user_treasure_relation> user_treasure_relation { get; set; }
    }
}
