//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindTheBooty.Models.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class treasure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public treasure()
        {
            this.awards = new HashSet<award>();
            this.badges = new HashSet<badge>();
            this.user_treasure_relation = new HashSet<user_treasure_relation>();
        }
    
        public int treasure_id { get; set; }
        public int hunt_hunt_id { get; set; }
        public string description { get; set; }
        public string seq_ffa { get; set; }
        public string confirmation { get; set; }
        public int points { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<award> awards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<badge> badges { get; set; }
        public virtual hunt hunt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_treasure_relation> user_treasure_relation { get; set; }
    }
}
